name: DVC Pipeline

on:
  push:
    branches: master

jobs:
  dvc_pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install DVC
        run: |
          pip install --upgrade dvc
          pip install dvc[gdrive]

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }} 

      - name: Configure DVC remote
        run: |
          dvc remote add -d gdrive_remote -f gdrive://${{ secrets.GOOGLE_CLOUD_EMAIL }}@${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com/14ngLTJjLfa_QoV8Y5aR6QicPg2qRM9jf

      - name: Pull data with DVC
        run: |
          dvc pull

      - name: Verify pipeline integrity
        run: |
          dvc repro
          dvc pull 

      - name: Verify pipeline integrity
        run: |
          dvc repro
