name: DVC Pipeline

on:
  push:
    branches: master

jobs:
  dvc_pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install DVC
        run: |
          sudo apt update && sudo apt install --only-upgrade openssl
          pip install --upgrade dvc dvc[gdrive]
          pip install --upgrade cryptography


      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.TEMP_JSON }} 

      - name: Configure DVC Remote
        run: |
          # Remove the remote if it exists
          dvc remote remove gdrive_remote || true
          # Add the remote again
          dvc remote add -d gdrive_remote gdrive://14ngLTJjLfa_QoV8Y5aR6QicPg2qRM9jf

      - name: Pull data with DVC
        run: |
          dvc pull

      - name: Verify pipeline integrity
        run: |
          dvc repro
